Repository MissouriMRR/SUAS-2022, pull requests merged in 2022-03, with the labels that each got.

#27 Find Alphanumeric character in image
  vision/Object Detection/standard_obj_text.py
Labels: enhancement

#30 Create a basic algorithm for stationary obstacle avoidance
  flight/Stationary Obstacle Avoidance/main.py
  flight/Stationary Obstacle Avoidance/math_functions.py
  flight/Stationary Obstacle Avoidance/obstacle_avoidance.py
  flight/Stationary Obstacle Avoidance/plotter.py
  flight/Stationary Obstacle Avoidance/sample_data.json
Labels: flight, feature, Obstacle Avoidance

#34 Add poetry python dependencies and dev dependencies
  pyproject.toml
Labels: enhancement

#37 Feature/setup gitattributes
  .gitattributes
  .pre-commit-config.yaml
  run.py
Labels: enhancement

#38 Feature/update precommit config
  .gitignore
  .mypy.ini
  .pre-commit-config.yaml
  .pylintrc
Labels: repo
